import "./globals.css";
import "../assets/fonts.css";
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
